# ----------------------- #
#     Site Variables      #
# ----------------------- #

name: Andreas Renberg (IQAndreas)
author: Andreas Renberg (IQAndreas)
url: 'http://www.iqandreas.com'

title: Andreas Renberg (IQAndreas)
displayed_title: <span id="andreas-renberg">Andreas Renberg</span>
subtitle: Known on the internet as <span id="iqandreas"><span id="iq">IQ</span><span id="andreas">Andreas</span></span>

#copyright_message: &copy;&nbsp;2013 by Andreas&nbsp;Renberg
github_license: The MIT License
github_license_url: https://github.com/IQAndreas/markdown-licenses/blob/master/mit.md


# ----------------------- #
#       Site Paths        #
# ----------------------- #

# LOCAL
stylesheets: /assets/stylesheets
javascripts: /assets/javascripts
images:      /assets/images
fonts:       /assets/fonts

# GLOBAL
global_stylesheets: http://static.iqandreas.com/assets/stylesheets
global_javascripts: http://static.iqandreas.com/assets/javascripts
global_images:      http://static.iqandreas.com/assets/images
global_fonts:       http://static.iqandreas.com/assets/fonts

# ----------------------- #
#     Plugin Configs      #
# ----------------------- #

google_analytics_id:   UA-44446017-1
google_analytics_name: iqandreas.com

source_title_prefix: "GitHub: IQAndreas/iqandreas.github.io"
source_url: 'https://github.com/IQAndreas/iqandreas.github.io/tree/master'

# ----------------------- #
#     Jekyll Configs      #
# ----------------------- #

#source: source
destination: _public
plugins: 	 _plugins

exclude: [update.sh]

relative_permalinks: false
markdown: redcarpet
pygments: true

